export default {
  fontFamily: "'Gotham Pro', Helvetica, Arial",
  radius: '8px',
  borderRadius: '8px',
  borderCircle: '100vw',
  borderSmall: '4px',
  gridGap: 8,
  tablePadding: 16,
  layout: {
    phone: 540,
    tablet: 720,
    smallDesktop: 960,
    largeDesktop: 1184,
  },
  colors: {
    main: '#4a4a4a',
    white: '#ffffff',
    secondary: '#9b9b9b',
    gray: '#cdcdcd',
    lightGray: '#f4f5f8',
    lighterGray: '#f2f3fa',
    primary: '#7070ff',
    darkPrimary: '#8C8CFF',
    darkestPrimary: '#5f5fe9',
    darkerGray: '#e2e4ee',
    darkestGray: '#cbcedc',
    focusPrimary: '#5555cf',
    focusPrimaryText: '#dedeff',
    semiPrimary: '#CFCFFF',
    lightPrimary: '#dedeff',
    lighterPrimary: '#f0f0ff',
    border: '#e3e3e3',
    success: '#50cc58',
    darkSuccess: '#4b9393',
    darkerSuccess: '#32cb54',
    danger: '#ee1e31',
    darkDanger: '#c61322',
    darkerDanger: '#d01d2d',
    lightDanger: '#fcd1d5',
    warning: '#fed305',
    darkWarning: '#ddb800',
    darkerWarning: '#e0d201',
    lightWarning: '#fff7cd',
    lighterBackground: '#f4f5fb',
    mainBackground: '#f8f9fd',
    darkerBackground: '#eeeff4',
    header: '#2a2a34',
    placeholder: '#808080',
    menu: '#6c6c73',
  },
};
